### ISSUE TITLE
Add optional pretty printing and/or writing to file

### ISSUE THREAD

**Issue by WoLpH** [raphaelm/python-sepaxml#14]
I know the code is easy enough to write yourself. But it would be convenient if the `export` function would take an optional `filename` parameter to write to. And an optional keyword argument `pretty=True` to make the output human readable.

**Comment by hennesdekok** [comment]
Is there now actually a way to save it to a file? Because I can't manage to save the string of the SEPA file to a certain file...

**Comment by WoLpH** [comment]
You can try this:
```python
with open('some_file.xml', 'w') as fh:
    fh.write(sepa.export(...))
```

**Comment by hennesdekok** [comment]
Raphaelm, many thanks for your response. I will try this out.

________________________________
Van: Rick van Hattem <notifications@github.com>
Verzonden: Wednesday, August 14, 2019 2:11:46 PM
Aan: raphaelm/python-sepaxml <python-sepaxml@noreply.github.com>
CC: hennesdekok <hennesdekok@hotmail.com>; Comment <comment@noreply.github.com>
Onderwerp: Re: [raphaelm/python-sepaxml] Add optional pretty printing and/or writing to file (#14)


You can try this:

with open('some_file.xml', 'w') as fh:
    fh.write(sepa.export(...))

**Comment by saddy001** [comment]
Pretty print it like this:

```
from lxml import etree

tree = etree.ElementTree(etree.fromstring(sepa.export(validate=True)))
xml = etree.tostring(tree, pretty_print=True, xml_declaration=True, encoding='utf-8').decode('utf-8')

with open('test.xml', 'w+') as f:
    f.write(xml)
```

**Comment by raphaelm** [comment]
Not adding pretty-print to this library, since it would require lxml as a dependency, which we currently don't have as a dependency. I do like lxml, but it can be nasty at times (e.g. it takes *ages* to compile lxml on a raspberry pi) and *just for pretty-printing* is not good enough a reason to add it.

**Comment by WoLpH** [comment]
You can pretty print without lxml too :)
https://stackoverflow.com/a/1206856/54017
minidom is bundled with python
