### ISSUE TITLE
schemas/ folder not getting installed

### ISSUE THREAD

**Issue by kpcyrd** [raphaelm/python-sepaxml#15]
While running the python-fints tests I ran into this error:
```
E           FileNotFoundError: [Errno 2] No such file or directory: '/usr/lib/python3.7/site-packages/sepaxml/schemas/pain.001.001.03.xsd'
```
It seems this is due to python-sepaxml not installing that folder. To install python-sepaxml I'm using:
```
python setup.py install -O1 --root="${pkgdir}"
```

I'm using the 2.1.0 release tar ball available on github.

**Comment by raphaelm** [comment]
Can you try if installing with pip works?

**Comment by pyropeter** [comment]
Yes, installing via pip works. That doesn't make a lot of sense, does it?

**Comment by pyropeter** [comment]
I see, I installed release 2.1.1 via pip, which contains commit 187b699b1673c862002b2bae7e1bd62fe8623aec, which likely fixed this issue. Could you create a GIT tag for release 2.1.1, so that @kpcyrd can bump his package to that version?

**Comment by raphaelm** [comment]
Sorry, somehow missed this. Will release today again!

**Comment by pyropeter** [comment]
No worries. Thanks for all the good work!
