### ISSUE TITLE
saving the SEPA file

### ISSUE THREAD

**Issue by hennesdekok** [raphaelm/python-sepaxml#18]
Hello, I can't find a way to save the created SEPA file. Could you give an example on how to do this? 
Also, when I try to change the type from for instance "pain.008.002.02" to "PAIN.001.001.03". The error message I get is as follows: "The output SEPA file contains validation errors. This is likely due to an illegal value in one of your input fields"

Many thanks in advance.

**Comment by raphaelm** [comment]
> Hello, I can't find a way to save the created SEPA file. Could you give an example on how to do this?

For example like this:

```
with open('file.xml', 'w') as f:
    f.write(sepa.export(validate=True))
```

> Also, when I try to change the type from for instance "pain.008.002.02" to "PAIN.001.001.03". The error message I get is as follows: "The output SEPA file contains validation errors. This is likely due to an illegal value in one of your input fields"

You can't just change the type, you also need to use ``SepaTransfer`` instead of ``SepaDD` in that case.
