### ISSUE TITLE
SEPA error

### ISSUE THREAD

**Issue by hennesdekok** [raphaelm/python-sepaxml#19]
When uploading the SEPA files to test-services like mobilefish.com, I keep receiving the same error: "Element '{urn:iso:std:iso:20022:tech:xsd:pain.001.001.03}CstmrDrctDbtInitn': This element is not expected. Expected is ( {urn:iso:std:iso:20022:tech:xsd:pain.001.001.03}CstmrCdtTrfInitn ).
". How can I change "CstmrDrctDbtInitn" to "CstmrCdtTrfInitn" ? Help is very appreciated!

thanks.

**Comment by raphaelm** [comment]
Can you show me the code you wrote? It looks like you're confusing debits and transfers.

**Comment by hennesdekok** [comment]
Basically i’m writing a gym membership management system that controls the accesgate, allows you to add, edit and remove certain members and handles the creation of SEPA files. I have to charge every member 22.50 euro’s. The problem is that i’m completely new to SEPA payments, and the only thing I want to do is create a SEPA file of type “pain.001.001.03”. I’m just trying stuff out with the code provided in the screenshot.

_________________________________________________________________________
from sepaxml import SepaDD
import datetime, uuid

config = {
    "name": "Test von Testenstein",
    "IBAN": "NL50BANK1234567890",
    "BIC": "BANKNL2A",
    "batch": True,
    "creditor_id": "DE26ZZZ00000000000",  # supplied by your bank or financial authority
    "currency": "EUR",  # ISO 4217
    #"instrument": "B2B"  # - default is CORE (B2C)
}
sepa = SepaDD(config, schema="pain.001.001.03", clean=True)

payment = {
    "name": "Test von Testenstein",
    "IBAN": "NL50BANK1234567890",
    "BIC": "BANKNL2A",
    "amount": 5000,  # in cents
    "type": "RCUR",  # FRST,RCUR,OOFF,FNAL
    "collection_date": datetime.date.today(),
    "mandate_id": "1234",
    "mandate_date": datetime.date.today(),
    "description": "Test transaction",
    #"endtoend_id": str(uuid.uuid1())  # autogenerated if obmitted
}
sepa.add_payment(payment)

with open('some_file.xml', 'w') as fh:
    fh.write(str(sepa.export(validate=False).decode('utf-8')))


________________________________
Van: Raphael Michel <notifications@github.com>
Verzonden: Thursday, August 15, 2019 6:10:01 PM
Aan: raphaelm/python-sepaxml <python-sepaxml@noreply.github.com>
CC: hennesdekok <hennesdekok@hotmail.com>; Author <author@noreply.github.com>
Onderwerp: Re: [raphaelm/python-sepaxml] SEPA error (#19)


Can you show me the code you wrote? It looks like you're confusing debits and transfers.

**Comment by raphaelm** [comment]
>  The problem is that i’m completely new to SEPA payments, and the only thing I want to do is create a SEPA file of type “pain.001.001.03”

Well, that's not going to happen. The ``pain.001`` formats are for SENDING money TO someone. If you want to CHARGE someone, you'll need the ``pain.008`` formats.

**Comment by hennesdekok** [comment]
I really appreciate your help. Now I can go further with the development of my first ever created software! Many thanks Raphael!

________________________________
Van: Raphael Michel <notifications@github.com>
Verzonden: Friday, August 16, 2019 8:50:08 AM
Aan: raphaelm/python-sepaxml <python-sepaxml@noreply.github.com>
CC: hennesdekok <hennesdekok@hotmail.com>; Author <author@noreply.github.com>
Onderwerp: Re: [raphaelm/python-sepaxml] SEPA error (#19)


The problem is that i’m completely new to SEPA payments, and the only thing I want to do is create a SEPA file of type “pain.001.001.03”

Well, that's not going to happen. The pain.001 formats are for SENDING money TO someone. If you want to CHARGE someone, you'll need the pain.008 formats.
