### ISSUE TITLE
Support country/address fields for international transfers

### ISSUE THREAD

**Issue by Codeberg-org** [raphaelm/python-sepaxml#28]
International transfers to some countries need country and postal address fields (Switzerland at least it seems, others like Danske bank mark this field as optional).

These are currently not supported:

```xml
    <!-- from  -->
    <Dbtr>
      <Nm>XXXXX</Nm> 
      <PstlAdr>
        <PstCd>75001</PstCd>
        <TwnNm>TwnNm</TwnNm>>
        <Ctry>CC</Ctry>
        <AdrLine>XXXXXX </AdrLine>
        <AdrLine>XXXXXX </AdrLine>
      </PstlAdr>
      <Id>
        <OrgId>
          <Othr>
          </Othr>
        </OrgId>
      </Id>
    </Dbtr>
```

It would be nice to support international DD from these countries.

**Comment by raphaelm** [comment]
I'd be very surprised if cross-country non-SEPA DD actually works, do banks really do that?
It'd be interested for CT, though, yes.

**Comment by Codeberg-org** [comment]
These are actual SEPA DD transfers, as described [here](https://cashmanagement.bnpparibas.com/_webdata/sepa-guide-pdf/bnpp_sepa_country_guide_-_switzerland.pdf) and [here](https://www.six-group.com/en/products-services/banking-services/standardization.html#scrollTo=participation-sepa-direct-debit). For some reasons, some banks in those countries "just work" with "local"/EU rules, whereas others apply stricter checks. Beside Switzerland we have seen these with Finnish banks recently.

With GB, we just learned that due to Brexit [as of 2021-12-31 SEPA transfers require the full address too](https://www.sfirm.de/nc/aktuelle-meldungen/aktuelles/article//brexit-und-sepa-lastschriften.html).

**Comment by jonatandmapser** [comment]
Hello! Is there an option to put the address in these cases?
Thanks!

**Comment by raphaelm** [comment]
This finally is implemented now :)
