### ISSUE TITLE
pip install doesn't work with Python3.7

### ISSUE THREAD

**Issue by afoufou** [raphaelm/python-sepaxml#37]
Hi all, 

`pip install sepa xml` doesn't work with python 3.7 and pip 18.1. 
 There is a syntax error in validation.py

Following, the error found

> Complete output from command python setup.py egg_info:
Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-RIMfI7/sepaxml/setup.py", line 6, in <module>
        from sepaxml import version
      File "sepaxml/__init__.py", line 1, in <module>
        from .debit import SepaDD  # noqa
      File "sepaxml/debit.py", line 4, in <module>
        from .shared import SepaPaymentInitn
      File "sepaxml/shared.py", line 5, in <module>
        from .validation import try_valid_xml
      File "sepaxml/validation.py", line 18
        ) from e
             ^
    SyntaxError: invalid syntax
    ----------------------------------------
    Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-RIMfI7/sepaxml/

**Comment by bibz** [comment]
Are you stuck with pip 18.1? That's a three year-old version (October 2018). You are bound to encounter error with this old pip.
I'd suggest first updating pip in your virtual environment with `pip install --upgrade pip` before installing `sepaxml`.

I have no problem with python 3.7.10 and the latest pip (21.2.4, published in August 2021).
