### ISSUE TITLE
Do not use this

### ISSUE THREAD

**Issue by michaelbrunnbauer** [raphaelm/python-sepaxml#42]
Author has lost interest (see issue list).
Probably does not support the SEPA version your bank wants from you.

**Comment by raphaelm** [comment]
I have not entirely lost interest, I still intend to support newer SEPA versions, I just have a lack of time on my hands.

The annoying thing is that codebase is a little bit of mess and hard to extend. I did not write this code, I mostly took existing free code and packaged and tested it properly. :\

**Comment by michaelbrunnbauer** [comment]
Sorry for venting my frustration after my bank stopped supporting pain.008.002.02 without prior announcement. It turned out they still support pain.008.003.02 - which is supported by sepaxml. Unfortunately, my bank will phase out pain.008.003.02 next November - so you have one year :-)

Whoever is behind those standards is not of this world but on the spot with naming.

**Comment by raphaelm** [comment]
I had the same issue with my bank yesterday and went the quick route of just changing the version number in the file by hand, yes… Glad you found a workaround for now ;)
