### ISSUE TITLE
How to provide "Kundendaten" (customer reference) to a SEPA transfer?

### ISSUE THREAD

**Issue by haimat** [raphaelm/python-sepaxml#50]
When issuing a SEPA transfer via online banking, one can provide both a description as well as a customer/payment reference ("Kundendaten") value. The latter would be where one can insert the invoice number for example, which this transfer would be the payment for.

How can I provide this reference number with `python-sempaxml` via `add_payment()`?

**Comment by raphaelm** [comment]
Unfortunately I don't know which field your bank labels "Kundendaten". Maybe the End-to-End-ID?

**Comment by raphaelm** [comment]
🤷‍♂️

You can have a look eg here:
https://www.hettwer-beratung.de/sepa-spezialwissen/sepa-glossar/

"Remittance Information" is the classic "Verwendungszweck". "End to end ID" might be what you are looking for, but I don't know for sure. My online banking does not have either 

What bank are you using?

**Comment by haimat** [comment]
@raphaelm Thanks, it turned out you're right - it was the End-to-End ID :+1:
