### ISSUE TITLE
Broken FinInstnId

### ISSUE THREAD

**Issue by FrankKipf** [raphaelm/python-sepaxml#61]
Adding a payment without BIC leads to a broken `<FinInstnId>`

It should look like this:

`<DrctDbtTxInf>
...
<DbtrAgt>
   <FinInstnId>
      <Othr>
          <Id>NOTPROVIDED</Id>
       </Othr>
    </FinInstnId>
</DbtrAgt>
...
</DrctDbtTxInf>`

But instead I receive that output:

`<DrctDbtTxInf>
...
<DbtrAgt>
   <FinInstnId/>
</DbtrAgt>
...
</DrctDbtTxInf>`

I'm not sure, but I think in debit.py line 268 and line 269 have to be swapped with each other.

**Comment by Varchibald** [comment]
I have the same issue. Did you find a fix?

**Comment by FrankKipf** [comment]
I added a BIC to each payment. If you don't have the BIC, take a look at openiban.com

**Comment by Varchibald** [comment]
I need BICs from a broader range of countries than what is supported by openiban, unfortunately. I posted my solution, maybe I'll open a PR later.

**Comment by Varchibald** [comment]
@raphaelm do you know why this condition was put in there?

**Comment by raphaelm** [comment]
No, not reall

**Comment by Varchibald** [comment]
I assume the original merge @ https://github.com/raphaelm/python-sepaxml/pull/25 wanted the BIC-notprovided interaction only for their format (pain.008.003.02), so they excluded the other formats for fault of testing. Imo it shouldn't cause any issues if the exception is removed.

**Comment by dominikschopf** [comment]
This condition is simply wrong still. Also for pain.008.001.02, according to the German Bundesbank, see docs https://www.bundesbank.de/resource/blob/877540/eec34592d2bf123596897cf29448e04b/mL/technische-spezifikationen-sepa-lastschriften-2023-11-data.pdf

> Bei nationalen und grenzüberschreitenden SEPA-Lastschriften (CORE/B2B) ist die
Angabe des BIC des Zahlungsdienstleisters des Zahlers grundsätzlich entbehrlich; sofern auf die Angabe des BIC verzichtet wird, ist das Element <DbtrAgt><FinInstnId>
<Othr> <Id> mit der Konstante NOTPROVIDED zu belegen. 


(Translated by DeepL)

> For national and cross-border SEPA direct debits (CORE/B2B), it is generally not necessary to specify the BIC of the payer's payment service provider; if the BIC is not specified, the element <DbtrAgt><FinInstnId><Othr><Id> must be assigned the constant NOTPROVIDED. 

IMO, the `elif` [here](https://github.com/raphaelm/python-sepaxml/blob/master/sepaxml/debit.py#L345) should simply be replaced by an `else`.

**Comment by raphaelm** [comment]
I currently do not have the time to look at this until it is a case that affects us, but I'm happy to accept PRs that fix it.

**Comment by dominiks96** [comment]
@raphaelm I'll give it a shot and create a PR. 

Would be cool, if you could assemble a release including the fix soon. Otherwise, using it is kind of a lot of effort for most of the users probably.

**Comment by dominiks96** [comment]
@raphaelm PR is here. I tested it in the commerzbank online portal and also using the [windata](https://www.windata.de/) app

**Comment by pascom-devs** [comment]
@raphaelm Mind publishing the new version on PyPi? I believe for you it's just the click of a button.

**Comment by raphaelm** [comment]
Yup, somehow it did not end up on PyPI, fixed now.
